### ISSUE TITLE
conflict between this extension and pythongosssss custom-scripts

### ISSUE THREAD

**Issue by koko93s** [syllebra/bilbox-comfyui#10]
Hello, 

There is a conflict between the style sheets for your extension and the one in [https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/173](url).  This link is to the issue on that repo.  For some reason pythongs extension css is being overridden by yours.  Not sure who to talk to about this but I've left issues on both repos pointing at one another.   The picture below is from the view info window from pythong.  All the text crammed in the upper right corner should be located under notes / civitai, etc.

Thanks!

![Screenshot (65)](https://github.com/syllebra/bilbox-comfyui/assets/36585095/bc0aebcb-7158-4fed-ac22-83b3fde18e01)

**Comment by marduk191** [comment]
yes, this node pack has a ton of egregious css code that messes up many nodes and interfaces, I don't recommend using it.
