### ISSUE TITLE
Feature request: Add option to hide the new "Server" button from menu

### ISSUE THREAD

**Issue by Apacchi88** [syllebra/bilbox-comfyui#12]
It takes up unnecessary space if not using it, allow user to hide the added button and separators.

**Comment by GalaxyTimeMachine** [comment]
I agree, this has no place in the ComfyUI.

**Comment by Neytiri7** [comment]
\ComfyUI\custom_nodes\bilbox-comfyi\web If you delete this 'reboot.js' here, it doesn't show up.

When it's updated, it looks like it can happen again.
I have no choice but to manually erase it.

**Comment by GalaxyTimeMachine** [comment]
You could delete the file and then add it to the .gitignore, so it doesn't add it back in again.

**Comment by Neytiri7** [comment]
How do you do it??
And, I want the developer to see this.

**Comment by syllebra** [comment]
Hello, and sorry for the delay.
This feature is purely personnal ,because I mainly use ComfyUI on a distant self hosted server that I want to turn off directly in the UI.

I understand the problem and I would be glad to add an option but I need to make some recearch to add it properly in ComfyUI.

**Comment by Neytiri7** [comment]
Then, when I delete the reboot.js file, I wonder how to prevent it from reviving when I update it.
I think it's a necessary method for users who don't use that function.

**Comment by syllebra** [comment]
I syhould completely remove it now. In the meantime, just switch to new menu in comfy UI.

**Comment by syllebra** [comment]
I added a specific option in comfy ui parameters.
