### ISSUE TITLE
Prompt not changing in preview or output.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [syllebra/bilbox-comfyui#13]
I could really make a lot of use of this node, and it's sometimes very useful....but it's so unreliable :(

You can see in the image below that I've changed the prompt (a few times) but the preview and resulting output is exactly the same as the first prompt I used. The only way I can make it change is to change something in one of the node's options. This shouldn't be required to register a change on the prompt.

![image](https://github.com/syllebra/bilbox-comfyui/assets/52193044/50c3b579-16dc-4edb-a690-f49bbbbf5dab)

Here I added a photographer and the prompt then updated:

![image](https://github.com/syllebra/bilbox-comfyui/assets/52193044/f80db1cc-1327-4c67-a468-266f34761bc1)

**Comment by GalaxyTimeMachine** [comment]
Is this still being maintained?

**Comment by endlessblink** [comment]
Same thing happened to me. The temporary workaround is changing some other parameter and then it updates. Hopefully it get sorted out officially sometime.  @GalaxyTimeMachine

**Comment by syllebra** [comment]
I think it is related to #3. I will try to fix it some day, sorry for this annoying bug

**Comment by syllebra** [comment]
Should be fixed now...
