### ISSUE TITLE
the styles previews are empty. where to fill them with images?

### ISSUE THREAD

**Issue by rafstahelin** [syllebra/bilbox-comfyui#22]
not sure but when i select lighting or another category, the thumbnail preview opens, but no tn show up. do i need to copy files into there? can i customise these with my own? no readme about this in the repo. thanks

**Comment by davoodice** [comment]
load comfyui in legecy mode

**Comment by Trife66** [comment]
I loaded in Legacy mode still not showing

**Comment by Trife66** [comment]
> load comfyui in legecy mode
I loaded in Legacy mode still not showing?

**Comment by Skuuurt** [comment]
> load comfyui in legecy mode

Things are generally done in order to avoid roll back.
That is up to the devs to update their node accordingly on that one if you ask me.

**Comment by davoodice** [comment]
According my test it is not a special thing. Just some prompts that are not work as you think. The node works buggy and will frrastrat you.
