### ISSUE TITLE
It's not work after convert the widget to input

### ISSUE THREAD

**Issue by nemo1105** [syllebra/bilbox-comfyui#3]
If I convert subject to input, the subject's value will not work. It will keep the value of it's widget form.

**Comment by syllebra** [comment]
Hi, sorry for delay. Yes, it's a known bug and it is not meant to be used like this for now. I did this to have a full interactive preview. Thus, only "inside" values are used (only JS code). If using widgets as inputs, I won't be able to preview result dynamically. TODO...

**Comment by nemo1105** [comment]
I'm not sure the "OUTPUT_NODE" attribute can do this?
I saw some custom nodes use this to do some api communication with serverside. The PREVIEW_STRING can be provided by serverside.

**Comment by syllebra** [comment]
Thank you I will tak ea look when I find some time...

**Comment by nemo1105** [comment]
> I'm not sure the "OUTPUT_NODE" attribute can do this? I saw some custom nodes use this to do some api communication with serverside. The PREVIEW_STRING can be provided by serverside.

I figured it out, if there is no OUTPUT_NODE, the workflow will not run...😅

**Comment by Latentnaut** [comment]
This looks an amazing project but sadly I also found the node buggy. Hope you can polish it :)

**Comment by GalaxyTimeMachine** [comment]
This is a problem for me too. I want to be able to use wildcards, which this node can not recognise, so I create the prompt in a node that does use wildcards and feed it into this one....and it is completely ignored :(

**Comment by ruucm** [comment]
here is a hotfix for this issue.

https://github.com/syllebra/bilbox-comfyui/pull/19

It looks there are changes to disable do the `node.type` check from ComfyUI.

**Comment by syllebra** [comment]
I commited the hot fix and it works now. However, you still need to select another parameter for auto update if nodes linked to widget input are modified.
