### ISSUE TITLE
Colab Issue: Bilbox copies images to WebUI every time Comfy is restarted

### ISSUE THREAD

**Issue by var1ableX** [syllebra/bilbox-comfyui#5]
Could you please add some kind of check to avoid loading the images every time comfy is restarted? This might be fast on local, but takes 2mins+ on Colab. Here's some sample code, I would have created a pull request but figure this might be a hack if you need some way to override the check if you update images ...

import shutil, os
import folder_paths

bx_path = os.path.dirname(__file__)
comfy_path = os.path.dirname(folder_paths.__file__)
dest_path = os.path.join(comfy_path, "web", "extensions")

destination = os.path.join(dest_path,"bilbox")

if not os.path.exists(destination):
    shutil.copytree(os.path.join(bx_path,"web_to_copy"), destination)
else:
    print(f"The destination path {destination} already exists.")

**Comment by syllebra** [comment]
You are right, I did not think about colab usage. I was doing this on the begining but indeed, it was a pita when changing js code. Will do on a more stable version?

**Comment by syllebra** [comment]
It seems that Comfyui is begining to develop an "extension" mechanism in which copy will not be need. For now it only works for javascripts afaik. Going in the good direction... A temporary solution could be disable the copy code and make a symlink...

**Comment by syllebra** [comment]
Should be fixed now. Just remove the "bilbox" directory under web if you don't make a frash install...
