### ISSUE TITLE
BilboX post-processing LUT does not recognize files ending with .CUBE

### ISSUE THREAD

**Issue by cjps-br** [syllebra/bilbox-comfyui#7]
If the lut file extension is in capital letters (.CUBE) the file is not recognized by the node.

As an attempt at a solution, I put the file names ending in lowercase, but I would like to make a suggestion:

line 13 of the read_luts_dicts function could be modified to:

if file.lower().endswith('.cube'):

this way the node would recognize both the .cube and .CUBE extensions.

**Comment by syllebra** [comment]
Yup, small glitch. Should be fixed now....
